# Generated by Django 3.1.1 on 2020-09-14 07:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='watchlist',
            options={'ordering': ['-added']},
        ),
        migrations.AddField(
            model_name='watchlist',
            name='movie_poster',
            field=models.URLField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('movie_id', 'user')},
        ),
    ]
